#!/usr/bin/env bash
#
#

initcolors() {
	# colors
	esc=""
	redf="${esc}[31m";
	greenf="${esc}[32m"
	yellowf="${esc}[33m"
	bluef="${esc}[34m";
	purplef="${esc}[35m"
	cyanf="${esc}[36m";
	reset="${esc}[0m";

	# circles
	cred="${redf} ${reset}"
	cgreen="${greenf} ${reset}"
	cyellow="${yellowf} ${reset}"
	cblue="${bluef} ${reset}"
	cpurple="${purplef} ${reset}"
	ccyan="${cyanf} ${reset}"
}
initcolors

config=("date" "time" "kernel" "uptime")
weather_city="Pécs"
disk_path=("/dev/sda1")

time_prefix=""
kernel_prefix=""
uptime_prefix=""
date_prefix=""


for val in ${config[*]}; do
	case $val in
		time)
			time="$(date +"%H:%M %p")"
			argconf+=$cred' '$time_prefix' '$time'\n'
			;;
		date)
			date="$(date +"%a %F")"
			argconf+=$cblue' '$date_prefix' '$date'\n'
			;;
		kernel)
			kern="$(uname -sr | sed 's/-.*//')"
			argconf+=$cyellow' '$kernel_prefix' '$kern'\n'
			;;
		uptime)
			upt="$(uptime -p | sed 's/up //')"
			argconf+=$cgreen' '$uptime_prefix' '$upt'\n'
			;;
	esac
done

echo ""
echo -ne $argconf
echo ""
